// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package drivers.protobuf;

public final class Msg {
    private Msg() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface NodeOrBuilder extends
            // @@protoc_insertion_point(interface_extends:drivers.protobuf.Node)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.drivers.protobuf.Node child1 = 1;</code>
         */
        boolean hasChild1();
        /**
         * <code>.drivers.protobuf.Node child1 = 1;</code>
         */
        drivers.protobuf.Msg.Node getChild1();
        /**
         * <code>.drivers.protobuf.Node child1 = 1;</code>
         */
        drivers.protobuf.Msg.NodeOrBuilder getChild1OrBuilder();

        /**
         * <code>.drivers.protobuf.Node child2 = 2;</code>
         */
        boolean hasChild2();
        /**
         * <code>.drivers.protobuf.Node child2 = 2;</code>
         */
        drivers.protobuf.Msg.Node getChild2();
        /**
         * <code>.drivers.protobuf.Node child2 = 2;</code>
         */
        drivers.protobuf.Msg.NodeOrBuilder getChild2OrBuilder();
    }
    /**
     * Protobuf type {@code drivers.protobuf.Node}
     */
    public  static final class Node extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:drivers.protobuf.Node)
            NodeOrBuilder {
        // Use Node.newBuilder() to construct.
        private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Node() {
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Node(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            drivers.protobuf.Msg.Node.Builder subBuilder = null;
                            if (child1_ != null) {
                                subBuilder = child1_.toBuilder();
                            }
                            child1_ = input.readMessage(drivers.protobuf.Msg.Node.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(child1_);
                                child1_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            drivers.protobuf.Msg.Node.Builder subBuilder = null;
                            if (child2_ != null) {
                                subBuilder = child2_.toBuilder();
                            }
                            child2_ = input.readMessage(drivers.protobuf.Msg.Node.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(child2_);
                                child2_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return drivers.protobuf.Msg.internal_static_drivers_protobuf_Node_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return drivers.protobuf.Msg.internal_static_drivers_protobuf_Node_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            drivers.protobuf.Msg.Node.class, drivers.protobuf.Msg.Node.Builder.class);
        }

        public static final int CHILD1_FIELD_NUMBER = 1;
        private drivers.protobuf.Msg.Node child1_;
        /**
         * <code>.drivers.protobuf.Node child1 = 1;</code>
         */
        public boolean hasChild1() {
            return child1_ != null;
        }
        /**
         * <code>.drivers.protobuf.Node child1 = 1;</code>
         */
        public drivers.protobuf.Msg.Node getChild1() {
            return child1_ == null ? drivers.protobuf.Msg.Node.getDefaultInstance() : child1_;
        }
        /**
         * <code>.drivers.protobuf.Node child1 = 1;</code>
         */
        public drivers.protobuf.Msg.NodeOrBuilder getChild1OrBuilder() {
            return getChild1();
        }

        public static final int CHILD2_FIELD_NUMBER = 2;
        private drivers.protobuf.Msg.Node child2_;
        /**
         * <code>.drivers.protobuf.Node child2 = 2;</code>
         */
        public boolean hasChild2() {
            return child2_ != null;
        }
        /**
         * <code>.drivers.protobuf.Node child2 = 2;</code>
         */
        public drivers.protobuf.Msg.Node getChild2() {
            return child2_ == null ? drivers.protobuf.Msg.Node.getDefaultInstance() : child2_;
        }
        /**
         * <code>.drivers.protobuf.Node child2 = 2;</code>
         */
        public drivers.protobuf.Msg.NodeOrBuilder getChild2OrBuilder() {
            return getChild2();
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (child1_ != null) {
                output.writeMessage(1, getChild1());
            }
            if (child2_ != null) {
                output.writeMessage(2, getChild2());
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (child1_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getChild1());
            }
            if (child2_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getChild2());
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof drivers.protobuf.Msg.Node)) {
                return super.equals(obj);
            }
            drivers.protobuf.Msg.Node other = (drivers.protobuf.Msg.Node) obj;

            boolean result = true;
            result = result && (hasChild1() == other.hasChild1());
            if (hasChild1()) {
                result = result && getChild1()
                        .equals(other.getChild1());
            }
            result = result && (hasChild2() == other.hasChild2());
            if (hasChild2()) {
                result = result && getChild2()
                        .equals(other.getChild2());
            }
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasChild1()) {
                hash = (37 * hash) + CHILD1_FIELD_NUMBER;
                hash = (53 * hash) + getChild1().hashCode();
            }
            if (hasChild2()) {
                hash = (37 * hash) + CHILD2_FIELD_NUMBER;
                hash = (53 * hash) + getChild2().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static drivers.protobuf.Msg.Node parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static drivers.protobuf.Msg.Node parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static drivers.protobuf.Msg.Node parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static drivers.protobuf.Msg.Node parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static drivers.protobuf.Msg.Node parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static drivers.protobuf.Msg.Node parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static drivers.protobuf.Msg.Node parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static drivers.protobuf.Msg.Node parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static drivers.protobuf.Msg.Node parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static drivers.protobuf.Msg.Node parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(drivers.protobuf.Msg.Node prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code drivers.protobuf.Node}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:drivers.protobuf.Node)
                drivers.protobuf.Msg.NodeOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return drivers.protobuf.Msg.internal_static_drivers_protobuf_Node_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return drivers.protobuf.Msg.internal_static_drivers_protobuf_Node_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                drivers.protobuf.Msg.Node.class, drivers.protobuf.Msg.Node.Builder.class);
            }

            // Construct using drivers.protobuf.Msg.Node.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                if (child1Builder_ == null) {
                    child1_ = null;
                } else {
                    child1_ = null;
                    child1Builder_ = null;
                }
                if (child2Builder_ == null) {
                    child2_ = null;
                } else {
                    child2_ = null;
                    child2Builder_ = null;
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return drivers.protobuf.Msg.internal_static_drivers_protobuf_Node_descriptor;
            }

            public drivers.protobuf.Msg.Node getDefaultInstanceForType() {
                return drivers.protobuf.Msg.Node.getDefaultInstance();
            }

            public drivers.protobuf.Msg.Node build() {
                drivers.protobuf.Msg.Node result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public drivers.protobuf.Msg.Node buildPartial() {
                drivers.protobuf.Msg.Node result = new drivers.protobuf.Msg.Node(this);
                if (child1Builder_ == null) {
                    result.child1_ = child1_;
                } else {
                    result.child1_ = child1Builder_.build();
                }
                if (child2Builder_ == null) {
                    result.child2_ = child2_;
                } else {
                    result.child2_ = child2Builder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof drivers.protobuf.Msg.Node) {
                    return mergeFrom((drivers.protobuf.Msg.Node)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(drivers.protobuf.Msg.Node other) {
                if (other == drivers.protobuf.Msg.Node.getDefaultInstance()) return this;
                if (other.hasChild1()) {
                    mergeChild1(other.getChild1());
                }
                if (other.hasChild2()) {
                    mergeChild2(other.getChild2());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                drivers.protobuf.Msg.Node parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (drivers.protobuf.Msg.Node) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private drivers.protobuf.Msg.Node child1_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    drivers.protobuf.Msg.Node, drivers.protobuf.Msg.Node.Builder, drivers.protobuf.Msg.NodeOrBuilder> child1Builder_;
            /**
             * <code>.drivers.protobuf.Node child1 = 1;</code>
             */
            public boolean hasChild1() {
                return child1Builder_ != null || child1_ != null;
            }
            /**
             * <code>.drivers.protobuf.Node child1 = 1;</code>
             */
            public drivers.protobuf.Msg.Node getChild1() {
                if (child1Builder_ == null) {
                    return child1_ == null ? drivers.protobuf.Msg.Node.getDefaultInstance() : child1_;
                } else {
                    return child1Builder_.getMessage();
                }
            }
            /**
             * <code>.drivers.protobuf.Node child1 = 1;</code>
             */
            public Builder setChild1(drivers.protobuf.Msg.Node value) {
                if (child1Builder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    child1_ = value;
                    onChanged();
                } else {
                    child1Builder_.setMessage(value);
                }

                return this;
            }
            /**
             * <code>.drivers.protobuf.Node child1 = 1;</code>
             */
            public Builder setChild1(
                    drivers.protobuf.Msg.Node.Builder builderForValue) {
                if (child1Builder_ == null) {
                    child1_ = builderForValue.build();
                    onChanged();
                } else {
                    child1Builder_.setMessage(builderForValue.build());
                }

                return this;
            }
            /**
             * <code>.drivers.protobuf.Node child1 = 1;</code>
             */
            public Builder mergeChild1(drivers.protobuf.Msg.Node value) {
                if (child1Builder_ == null) {
                    if (child1_ != null) {
                        child1_ =
                                drivers.protobuf.Msg.Node.newBuilder(child1_).mergeFrom(value).buildPartial();
                    } else {
                        child1_ = value;
                    }
                    onChanged();
                } else {
                    child1Builder_.mergeFrom(value);
                }

                return this;
            }
            /**
             * <code>.drivers.protobuf.Node child1 = 1;</code>
             */
            public Builder clearChild1() {
                if (child1Builder_ == null) {
                    child1_ = null;
                    onChanged();
                } else {
                    child1_ = null;
                    child1Builder_ = null;
                }

                return this;
            }
            /**
             * <code>.drivers.protobuf.Node child1 = 1;</code>
             */
            public drivers.protobuf.Msg.Node.Builder getChild1Builder() {

                onChanged();
                return getChild1FieldBuilder().getBuilder();
            }
            /**
             * <code>.drivers.protobuf.Node child1 = 1;</code>
             */
            public drivers.protobuf.Msg.NodeOrBuilder getChild1OrBuilder() {
                if (child1Builder_ != null) {
                    return child1Builder_.getMessageOrBuilder();
                } else {
                    return child1_ == null ?
                            drivers.protobuf.Msg.Node.getDefaultInstance() : child1_;
                }
            }
            /**
             * <code>.drivers.protobuf.Node child1 = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    drivers.protobuf.Msg.Node, drivers.protobuf.Msg.Node.Builder, drivers.protobuf.Msg.NodeOrBuilder>
            getChild1FieldBuilder() {
                if (child1Builder_ == null) {
                    child1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            drivers.protobuf.Msg.Node, drivers.protobuf.Msg.Node.Builder, drivers.protobuf.Msg.NodeOrBuilder>(
                            getChild1(),
                            getParentForChildren(),
                            isClean());
                    child1_ = null;
                }
                return child1Builder_;
            }

            private drivers.protobuf.Msg.Node child2_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    drivers.protobuf.Msg.Node, drivers.protobuf.Msg.Node.Builder, drivers.protobuf.Msg.NodeOrBuilder> child2Builder_;
            /**
             * <code>.drivers.protobuf.Node child2 = 2;</code>
             */
            public boolean hasChild2() {
                return child2Builder_ != null || child2_ != null;
            }
            /**
             * <code>.drivers.protobuf.Node child2 = 2;</code>
             */
            public drivers.protobuf.Msg.Node getChild2() {
                if (child2Builder_ == null) {
                    return child2_ == null ? drivers.protobuf.Msg.Node.getDefaultInstance() : child2_;
                } else {
                    return child2Builder_.getMessage();
                }
            }
            /**
             * <code>.drivers.protobuf.Node child2 = 2;</code>
             */
            public Builder setChild2(drivers.protobuf.Msg.Node value) {
                if (child2Builder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    child2_ = value;
                    onChanged();
                } else {
                    child2Builder_.setMessage(value);
                }

                return this;
            }
            /**
             * <code>.drivers.protobuf.Node child2 = 2;</code>
             */
            public Builder setChild2(
                    drivers.protobuf.Msg.Node.Builder builderForValue) {
                if (child2Builder_ == null) {
                    child2_ = builderForValue.build();
                    onChanged();
                } else {
                    child2Builder_.setMessage(builderForValue.build());
                }

                return this;
            }
            /**
             * <code>.drivers.protobuf.Node child2 = 2;</code>
             */
            public Builder mergeChild2(drivers.protobuf.Msg.Node value) {
                if (child2Builder_ == null) {
                    if (child2_ != null) {
                        child2_ =
                                drivers.protobuf.Msg.Node.newBuilder(child2_).mergeFrom(value).buildPartial();
                    } else {
                        child2_ = value;
                    }
                    onChanged();
                } else {
                    child2Builder_.mergeFrom(value);
                }

                return this;
            }
            /**
             * <code>.drivers.protobuf.Node child2 = 2;</code>
             */
            public Builder clearChild2() {
                if (child2Builder_ == null) {
                    child2_ = null;
                    onChanged();
                } else {
                    child2_ = null;
                    child2Builder_ = null;
                }

                return this;
            }
            /**
             * <code>.drivers.protobuf.Node child2 = 2;</code>
             */
            public drivers.protobuf.Msg.Node.Builder getChild2Builder() {

                onChanged();
                return getChild2FieldBuilder().getBuilder();
            }
            /**
             * <code>.drivers.protobuf.Node child2 = 2;</code>
             */
            public drivers.protobuf.Msg.NodeOrBuilder getChild2OrBuilder() {
                if (child2Builder_ != null) {
                    return child2Builder_.getMessageOrBuilder();
                } else {
                    return child2_ == null ?
                            drivers.protobuf.Msg.Node.getDefaultInstance() : child2_;
                }
            }
            /**
             * <code>.drivers.protobuf.Node child2 = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    drivers.protobuf.Msg.Node, drivers.protobuf.Msg.Node.Builder, drivers.protobuf.Msg.NodeOrBuilder>
            getChild2FieldBuilder() {
                if (child2Builder_ == null) {
                    child2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            drivers.protobuf.Msg.Node, drivers.protobuf.Msg.Node.Builder, drivers.protobuf.Msg.NodeOrBuilder>(
                            getChild2(),
                            getParentForChildren(),
                            isClean());
                    child2_ = null;
                }
                return child2Builder_;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:drivers.protobuf.Node)
        }

        // @@protoc_insertion_point(class_scope:drivers.protobuf.Node)
        private static final drivers.protobuf.Msg.Node DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new drivers.protobuf.Msg.Node();
        }

        public static drivers.protobuf.Msg.Node getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Node>
                PARSER = new com.google.protobuf.AbstractParser<Node>() {
            public Node parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Node(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Node> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Node> getParserForType() {
            return PARSER;
        }

        public drivers.protobuf.Msg.Node getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_drivers_protobuf_Node_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_drivers_protobuf_Node_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\tmsg.proto\022\020drivers.protobuf\"V\n\004Node\022&\n" +
                        "\006child1\030\001 \001(\0132\026.drivers.protobuf.Node\022&\n" +
                        "\006child2\030\002 \001(\0132\026.drivers.protobuf.Nodeb\006p" +
                        "roto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_drivers_protobuf_Node_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_drivers_protobuf_Node_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_drivers_protobuf_Node_descriptor,
                new java.lang.String[] { "Child1", "Child2", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}